import { Team, Product, TeamProduct, Order } from '../types'

export const MOCK_TEAMS: Team[] = [
  {
    id: 't1',
    slug: 'galatas',
    name: 'Gálatas Jiu-Jitsu',
    logo: 'https://img.usecurling.com/i?q=lion&color=solid-black&shape=fill',
    primaryColor: 'bg-neutral-900',
    coverImage: 'https://img.usecurling.com/p/1200/400?q=jiu%20jitsu%20training%20gym&color=black',
  },
  {
    id: 't2',
    slug: 'kataguruma',
    name: 'Kataguruma',
    logo: 'https://img.usecurling.com/i?q=shield&color=solid-black&shape=fill',
    primaryColor: 'bg-slate-900',
    coverImage: 'https://img.usecurling.com/p/1200/400?q=judo%20throw&color=blue',
  },
  {
    id: 't3',
    slug: 'galatas-king',
    name: 'Gálatas King',
    logo: 'https://img.usecurling.com/i?q=crown&color=solid-black&shape=fill',
    primaryColor: 'bg-neutral-900',
    coverImage: 'https://img.usecurling.com/p/1200/400?q=bjj%20black%20belt&color=black',
  },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Camiseta Regular',
    description: 'Camiseta versátil para uso casual e lifestyle no universo jiu-jitsu.',
    images: [
      'https://img.usecurling.com/p/600/800?q=black%20tshirt%20model&seed=1',
      'https://img.usecurling.com/p/600/800?q=white%20tshirt%20model&seed=2',
    ],
    category: 'Vestuário',
  },
  {
    id: 'p2',
    name: 'Camiseta Oversized',
    description: 'Modelagem ampla com estética contemporânea e lifestyle.',
    images: ['https://img.usecurling.com/p/600/800?q=white%20oversized%20tshirt&seed=3'],
    category: 'Vestuário',
  },
  {
    id: 'p3',
    name: 'Blusa Canguru',
    description: 'Blusa com bolso frontal e proposta premium esportiva.',
    images: ['https://img.usecurling.com/p/600/800?q=black%20hoodie&seed=4'],
    category: 'Vestuário',
  },
  {
    id: 'p4',
    name: 'Garrafa Inox Térmica',
    description: 'Garrafa inox com parede dupla, proposta premium e personalização exclusiva.',
    images: ['https://img.usecurling.com/p/600/800?q=thermos%20bottle&seed=5'],
    category: 'Acessórios',
  },
]

export const MOCK_TEAM_PRODUCTS: TeamProduct[] = [
  // 1. Galatas
  {
    id: 'tp1',
    teamId: 't1',
    productId: 'p1',
    price: 89.9,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Preto', 'Branco', 'Off White'],
    inStock: true,
    customizationFields: [
      {
        id: 'c1',
        name: 'modelo_personalizacao',
        label: 'Modelo da personalização',
        type: 'select',
        options: ['Galatas', 'Galatas King', 'Kataguruma'],
        required: true,
        price: 0,
      },
    ],
  },
  {
    id: 'tp2',
    teamId: 't1',
    productId: 'p2',
    price: 99.9,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Preto', 'Branco', 'Off White'],
    inStock: true,
    customizationFields: [
      {
        id: 'c2',
        name: 'modelo_personalizacao',
        label: 'Modelo da personalização',
        type: 'select',
        options: ['Galatas', 'Galatas King', 'Kataguruma'],
        required: true,
        price: 0,
      },
    ],
  },
  {
    id: 'tp3',
    teamId: 't1',
    productId: 'p3',
    price: 169.9,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Preto', 'Cinza'],
    inStock: true,
    customizationFields: [
      {
        id: 'c3',
        name: 'modelo_personalizacao',
        label: 'Modelo da personalização',
        type: 'select',
        options: ['Galatas', 'Galatas King', 'Kataguruma'],
        required: true,
        price: 0,
      },
    ],
  },
  {
    id: 'tp4',
    teamId: 't1',
    productId: 'p4',
    price: 129.9,
    sizes: [],
    colors: ['Preto', 'Branco'],
    models: ['Galatas', 'Galatas King', 'Kataguruma'],
    inStock: true,
    customizationFields: [
      {
        id: 'c4_1',
        name: 'nome_garrafa',
        label: 'Nome na garrafa',
        type: 'text',
        required: true,
        price: 0,
      },
      {
        id: 'c4_2',
        name: 'cor_personalizacao',
        label: 'Cor da personalização',
        type: 'select',
        options: ['Preto', 'Branco', 'Dourado'],
        required: false,
        price: 0,
      },
      {
        id: 'c4_3',
        name: 'grau_faixa',
        label: 'Grau da faixa',
        type: 'select',
        options: ['Branca', 'Azul', 'Roxa', 'Marrom', 'Preta'],
        required: true,
        price: 0,
      },
    ],
  },
  // 2. Kataguruma
  {
    id: 'tp5',
    teamId: 't2',
    productId: 'p1',
    price: 89.9,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Preto', 'Branco'],
    inStock: true,
    customizationFields: [
      {
        id: 'c5',
        name: 'modelo_personalizacao',
        label: 'Modelo da personalização',
        type: 'select',
        options: ['Kataguruma'],
        required: true,
        price: 0,
      },
    ],
  },
  {
    id: 'tp6',
    teamId: 't2',
    productId: 'p4',
    price: 129.9,
    sizes: [],
    colors: ['Preto', 'Branco'],
    models: ['Kataguruma'],
    inStock: true,
    customizationFields: [
      {
        id: 'c6_1',
        name: 'nome_garrafa',
        label: 'Nome na garrafa',
        type: 'text',
        required: true,
        price: 0,
      },
      {
        id: 'c6_2',
        name: 'cor_personalizacao',
        label: 'Cor da personalização',
        type: 'select',
        options: ['Preto', 'Branco', 'Verde'],
        required: false,
        price: 0,
      },
      {
        id: 'c6_3',
        name: 'grau_faixa',
        label: 'Grau da faixa',
        type: 'select',
        options: ['Branca', 'Azul', 'Roxa', 'Marrom', 'Preta'],
        required: true,
        price: 0,
      },
    ],
  },
  // 3. Galatas King
  {
    id: 'tp7',
    teamId: 't3',
    productId: 'p1',
    price: 94.9,
    sizes: ['P', 'M', 'G', 'GG'],
    colors: ['Preto', 'Branco', 'Off White'],
    inStock: true,
    customizationFields: [
      {
        id: 'c7',
        name: 'modelo_personalizacao',
        label: 'Modelo da personalização',
        type: 'select',
        options: ['Galatas King'],
        required: true,
        price: 0,
      },
    ],
  },
  {
    id: 'tp8',
    teamId: 't3',
    productId: 'p4',
    price: 134.9,
    sizes: [],
    colors: ['Preto', 'Branco'],
    models: ['Galatas King'],
    inStock: true,
    customizationFields: [
      {
        id: 'c8_1',
        name: 'nome_garrafa',
        label: 'Nome na garrafa',
        type: 'text',
        required: true,
        price: 0,
      },
      {
        id: 'c8_2',
        name: 'cor_personalizacao',
        label: 'Cor da personalização',
        type: 'select',
        options: ['Preto', 'Branco', 'Prata'],
        required: false,
        price: 0,
      },
      {
        id: 'c8_3',
        name: 'grau_faixa',
        label: 'Grau da faixa',
        type: 'select',
        options: ['Branca', 'Azul', 'Roxa', 'Marrom', 'Preta'],
        required: true,
        price: 0,
      },
    ],
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'BEJJ-0001',
    userId: 'u1',
    customerName: 'Victor',
    teamId: 't1',
    items: [
      {
        id: 'i1',
        teamProductId: 'tp1',
        productName: 'Camiseta Regular Galatas',
        teamName: 'Gálatas Jiu-Jitsu',
        price: 89.9,
        quantity: 1,
        size: 'M',
        color: 'Preto',
        customizations: {
          'Modelo da personalização': 'Galatas',
        },
        image: 'https://img.usecurling.com/p/600/800?q=black%20tshirt%20model&seed=1',
      },
      {
        id: 'i2',
        teamProductId: 'tp4',
        productName: 'Garrafa Inox Térmica Galatas',
        teamName: 'Gálatas Jiu-Jitsu',
        price: 129.9,
        quantity: 1,
        size: '',
        color: 'Branco',
        model: 'Galatas',
        customizations: {
          'Nome na garrafa': 'Victor',
          'Cor da personalização': 'Dourado',
          'Grau da faixa': 'Azul',
        },
        image: 'https://img.usecurling.com/p/600/800?q=thermos%20bottle&seed=5',
      },
    ],
    total: 219.8,
    paymentStatus: 'PENDING',
    productionStatus: 'PENDING',
    createdAt: '2026-03-18T10:30:00Z',
  },
]
